[workspace]
value_file = "signac_statepoint.json"

[default.action]
command = "python actions.py --action $ACTION_NAME {directories}"

[[action]]
name = "potential_energy_graph"
products = ['pe.svg']
launchers = ["openmp"]
group.maximum_size = 25
previous_actions = ['compute_data']

[action.resources]
threads_per_process = 1
walltime.per_submission = "00:02:30"

[[action]]
name = "rdf"
products = ['rdf.svg']
launchers = ["openmp"]
group.maximum_size = 25
previous_actions = ['compute_data']

[action.resources]
threads_per_process = 1
walltime.per_submission = "00:02:30"

[[action]]
name = "compute_data"
products = [
  'summary.txt',

  'log-0.txt',
  'log-1.txt',
  'log-2.txt',
  'log-3.txt',
  'log-4.txt',

  'trajectory-0.gsd',
  'trajectory-1.gsd',
  'trajectory-2.gsd',
  'trajectory-3.gsd',
  'trajectory-4.gsd',
]
launchers = ["openmp"]
group.maximum_size = 25

[action.resources]
gpus_per_process = 1
threads_per_process = 2
walltime.per_submission = "16:00:00"

[action.submit_options.borah]
setup = "module load openmpi"
custom = ["--gres=gpu:1"]
output_file_name = "out/{action_name}-%j.out"
partition = "gpu-v100"
