[workspace]
value_file = "signac_statepoint.json"

[default.action]
command = "python actions.py --action $ACTION_NAME {directories}"

[[action]]
name = "compute_data"
products = ['summary.txt']

[action.resources]
processes.per_submission = 1
gpus_per_process = 1
walltime.per_directory = "00:05:00"
